server:
    port: 8081
spring:
    application:
        name: recipe-service
    data:
        mongodb:
            uri: mongodb+srv://root:root@recipe-management-proje.u38h1hl.mongodb.net/?retryWrites=true&w=majority&appName=recipe-management-project
            database: recipe-management
app:
  image-directory: C:\Users\aayush_sharma\Desktop\ProjectImages\
