spring:
  application:
  name: Config-Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ashish0214/RecipePlatform-ConfigServer/tree/main
          clone-on-start: true
server:
  port: 8009
