server:
  port: 8765
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**, /otp/**
        - id: recipe-service
          uri: lb://recipe-service
          predicates:
            - Path=/recipes/**
          filters:
            - name: AuthenticationFilter